<item>
<title>[COLOR blue][B][I] S.W.A.T 1ª [/I][COLOR blue][I] (2017)[/I][/B][/COLOR]</title>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:02DAF67B4B13DA5478638989D705D00000CB508F&dn</link>
<thumbnail>https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg</thumbnail>
<fanart>https://www.themoviedb.org/t/p/original/AuY5Wuiwgc2CeuzM0I2poSe4E0x.jpg</fanart>
<info>[COLOR crimson][B][I] >>> globoplay <<< [/I][COLOR blue][I] Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu [/I][COLOR orange][I] Gêneros  [/I][COLOR white][I] >>> Crime, Drama <<< [/I][COLOR crimson][I] 42m [/I][B][/COLOR][/B]</info>
</item>
