<item>
<title>[COLOR blue][B][I] S.W.A.T [/I][COLOR blue] 1ª [COLOR blue][I] (2017)[/I][/B][/COLOR]</title>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:02DAF67B4B13DA5478638989D705D00000CB508F&dn</link>
<thumbnail>https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg</thumbnail>
<fanart>https://www.themoviedb.org/t/p/original/AuY5Wuiwgc2CeuzM0I2poSe4E0x.jpg</fanart>
<info>[COLOR crimson][B][I] >>> globoplay <<< [/I][COLOR blue][I] Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu [/I][COLOR orange][I] Gêneros  [/I][COLOR white][I] >>> Crime, Drama <<< [/I][COLOR crimson][I] 42m [/I][B][/COLOR][/B]</info>
</item>

<item>
<title>[COLOR blue][B][I] S.W.A.T [/I][COLOR blue] 2ª [COLOR blue][I] (2017) [/I][/B][/COLOR]</title>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:517f81c1c1330a72d3c4ed3cef1b8e50e86ede25&&dn$nome=[COLOR blue][B]1° 6° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:46179164fc6acaa31b52d04d35e029ccc6462969&&dn$nome=[COLOR blue][B]7° 12° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:1e120aecae0728a0415aa63c32d8358c31dd272a&&dn$nome=[COLOR blue][B]13° 18° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:52037f326c1d49d9be5c7652ed72c07faf20b9ff&&dn$nome=[COLOR blue][B]19° 23 Episodio[/B][/COLOR]</link>
<thumbnail>https://www.themoviedb.org/t/p/original/5LkqvZwp0LXzpumpnFp5eMgaMGE.jpg</thumbnail>
<fanart>https://www.themoviedb.org/t/p/original/i5lstlLwNmDgvZoIWLoBcD18bzR.jpg</fanart>
<info>[COLOR crimson][B][I] >>> globoplay <<< [/I][COLOR blue][I] Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu [/I][COLOR orange][I] Gêneros  [/I][COLOR white][I] >>> Crime, Drama <<< [/I][COLOR crimson][I] 42m [/I][B][/COLOR][/B]</info>
</item>

<item>
<title>[COLOR blue][B][I] S.W.A.T [/I][COLOR blue] 3ª [COLOR blue][I] (2020) [/I][/B][/COLOR]</title>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:c74722715120322152d4d51bb18cec0d5a424740&dn$nome=[COLOR blue][B]1° 2° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:3bac2108564f75a00e3d9e1f8e52f0f65559c650&dn$nome=[COLOR blue][B]3° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:9b1e11c010ed5c56166de3acde87363b819f2061&dn$nome=[COLOR blue][B]4° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:0d6f9dd3bb06600933ab9953656dc55da02b9dbf&dn$nome=[COLOR blue][B]5° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:1cae4a60ef768d6876b0e446ed5b60a40f2e01a7&dn$nome=[COLOR blue][B]6° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:43506a7040cff61f720fb7c5dbab8b07e1a26b24&dn$nome=[COLOR blue][B]7° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:3c2579613c0b184030eddcfd733691f41490070b&dn$nome=[COLOR blue][B]8° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:832350245a6761299d3da767332e6699824152d4&dn$nome=[COLOR blue][B]9° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:cfcdbafc8527c413373e19dc9019ceaf8b1cfa3f&dn$nome=[COLOR blue][B]10° 11° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:3c6a277d6efa9f56a49141656772dae77a1bf1d7&dn$nome=[COLOR blue][B]12° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:eb18ba7a5931e4e3b25c5ca2f378be9500355381&dn$nome=[COLOR blue][B]13° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:1298a319278a5fca79edd35a33226ad4c921dc15&dn$nome=[COLOR blue][B]14° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:1f4a2c1a86cec2b1bf109bf968b4c7b4e321bc36&dn$nome=[COLOR blue][B]15° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:7fc742cd763aec5b01abfb91065956ab5675a7c6&dn$nome=[COLOR blue][B]16° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:bdb0222070b1b9a50c1052c0bb7a8cbf6d3fe89c&dn$nome=[COLOR blue][B]17° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:e6258ee0b9a4ab6b0b6cef9f413520969238a37c&dn$nome=[COLOR blue][B]18° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:602629f9f463099591815a51c5327585303ddef7&dn$nome=[COLOR blue][B]19° Episodio[/B][/COLOR]</link>
<link>plugin://plugin.video.elementum/play?uri=magnet:?xt=urn:btih:ff457aec45f6e26f42eff5452910eaa7c9ba52f6&dn$nome=[COLOR blue][B]20° Episodio[/B][/COLOR]</link>
<thumbnail>https://www.themoviedb.org/t/p/original/dM1WYFrRtnkOZR1oVtCpBhscoPu.jpg</thumbnail>
<fanart>https://www.themoviedb.org/t/p/original/ybQvVsZ5KSnsrURlXuhg7xxWFPa.jpg</fanart>
<info>[COLOR blue][B][I] Torrent [/I][COLOR orange][I]  >>> [/I][/COLOR][/COLOR][COLOR blueviolet][I] Dividido entre a corporação e as ruas, o tenente Daniel Harrelson encara a missão de liderar uma unidade do Esquadrão de Armas e Táticas Especiais na comunidade onde cresceu [/I][COLOR orange][I] Gêneros  [/I][COLOR white][I] >>> Crime, Drama <<< [/I][COLOR crimson][I] 42m [/I][B][/COLOR][/B]</info>
</item>
